name: Deploy static site to Azure Web App - thematic

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'thematic'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_79C96A895A6B466CB615E43BA5AB3984 }}
          package: .
